### ISSUE TITLE
Implement a Simple Calculator with HTML, CSS, and JavaScript

### ISSUE THREAD

**Issue by AhmedAl-Bahrawy** [AhmedAl-Bahrawy/js-learning#1]
## Overview
Create a simple calculator web application using HTML, CSS, and JavaScript that supports basic arithmetic operations.

### Requirements
- Create a calculator interface with:
  - Number buttons (0-9)
  - Operation buttons (+, -, *, /)
  - Equals button (=)
  - Clear button (C)
  - Display area for input/result

#### HTML Structure
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Simple Calculator</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <div class="calculator">
        <div class="display">
            <input type="text" id="result" readonly>
        </div>
        <div class="buttons">
            <button class="clear">C</button>
            <button class="operator">/</button>
            <button class="number">7</button>
            <button class="number">8</button>
            <button class="number">9</button>
            <button class="operator">*</button>
            <button class="number">4</button>
            <button class="number">5</button>
            <button class="number">6</button>
            <button class="operator">-</button>
            <button class="number">1</button>
            <button class="number">2</button>
            <button class="number">3</button>
            <button class="operator">+</button>
            <button class="number">0</button>
            <button class="decimal">.</button>
            <button class="equals">=</button>
        </div>
    </div>
    <script src="script.js"></script>
</body>
</html>
```

#### CSS Styling
```css
.calculator {
    width: 300px;
    margin: 50px auto;
    padding: 20px;
    border-radius: 10px;
    background-color: #f2f2f2;
    box-shadow: 0 0 10px rgba(0,0,0,0.1);
}

.display input {
    width: 100%;
    height: 40px;
    margin-bottom: 10px;
    padding: 5px;
    font-size: 20px;
    text-align: right;
    border: none;
    background-color: white;
}

.buttons {
    display: grid;
    grid-template-columns: repeat(4, 1fr);
    gap: 5px;
}

button {
    padding: 15px;
    font-size: 18px;
    border: none;
    border-radius: 5px;
    cursor: pointer;
    background-color: #fff;
}

button:hover {
    background-color: #e0e0e0;
}

.operator {
    background-color: #f0f0f0;
}

.equals {
    background-color: #4CAF50;
    color: white;
}

.clear {
    background-color: #ff4444;
    color: white;
}
```

#### JavaScript Logic
```javascript
document.addEventListener('DOMContentLoaded', () => {
    let display = document.getElementById('result');
    let firstOperand = null;
    let operator = null;
    let waitingForSecondOperand = false;

    // Add click handlers to all buttons
    document.querySelectorAll('button').forEach(button => {
        button.addEventListener('click', () => {
            if (button.classList.contains('number')) {
                inputNumber(button.textContent);
            } else if (button.classList.contains('operator')) {
                inputOperator(button.textContent);
            } else if (button.classList.contains('equals')) {
                calculate();
            } else if (button.classList.contains('clear')) {
                clear();
            } else if (button.classList.contains('decimal')) {
                inputDecimal();
            }
        });
    });

    function inputNumber(number) {
        if (waitingForSecondOperand) {
            display.value = number;
            waitingForSecondOperand = false;
        } else {
            display.value = display.value === '0' ? number : display.value + number;
        }
    }

    function inputOperator(op) {
        const inputValue = parseFloat(display.value);
        
        if (firstOperand === null) {
            firstOperand = inputValue;
        } else if (operator) {
            const result = calculate();
            display.value = result;
            firstOperand = result;
        }
        
        waitingForSecondOperand = true;
        operator = op;
    }

    function calculate() {
        const secondOperand = parseFloat(display.value);
        let result = 0;
        
        switch (operator) {
            case '+':
                result = firstOperand + secondOperand;
                break;
            case '-':
                result = firstOperand - secondOperand;
                break;
            case '*':
                result = firstOperand * secondOperand;
                break;
            case '/':
                result = firstOperand / secondOperand;
                break;
            default:
                return;
        }
        
        operator = null;
        firstOperand = result;
        waitingForSecondOperand = true;
        display.value = result;
        return result;
    }

    function clear() {
        display.value = '0';
        firstOperand = null;
        operator = null;
        waitingForSecondOperand = false;
    }

    function inputDecimal() {
        if (!display.value.includes('.')) {
            display.value += '.';
        }
    }
});
```

### Features
1. Basic arithmetic operations: addition, subtraction, multiplication, and division
2. Clear button to reset the calculator
3. Decimal point support
4. Responsive design
5. Error handling for division by zero

### Testing
Please test the following scenarios:
1. Basic operations with whole numbers
2. Operations with decimal numbers
3. Multiple operations in sequence
4. Division by zero
5. Clear functionality
6. Display formatting and overflow

### Deliverables
- index.html file with the calculator structure
- styles.css file with the calculator styling
- script.js file with the calculator logic
- All files should be properly commented and formatted

### Notes
- The calculator should be responsive and work on both desktop and mobile devices
- All buttons should have hover effects for better user interaction
- The display should be read-only to prevent direct user input
- The calculator should handle basic error cases
